// <auto-generated />
using System;
using API_Camiones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Camiones.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Camiones.Modelos.Carga", b =>
                {
                    b.Property<int>("Idcarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcarga"));

                    b.Property<double>("Bonif")
                        .HasColumnType("float");

                    b.Property<bool?>("Borrado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("IdViaje")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("float");

                    b.Property<double>("PrecioUnit")
                        .HasColumnType("float");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Subtotal")
                        .HasColumnType("float");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcarga");

                    b.ToTable("Cargas");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Categoria", b =>
                {
                    b.Property<int>("Idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcategoria"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Factura", b =>
                {
                    b.Property<int>("Idfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idfactura"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Cargas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("Idfactura");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Gasto", b =>
                {
                    b.Property<int>("Idgasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idgasto"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int?>("Categoria")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Viaje")
                        .HasColumnType("int");

                    b.HasKey("Idgasto");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<bool?>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facturas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idusuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API_Camiones.Modelos.Viaje", b =>
                {
                    b.Property<int>("Idviaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idviaje"));

                    b.Property<bool?>("Borrado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int>("Cp")
                        .HasColumnType("int");

                    b.Property<int>("CuitUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<bool>("Facturado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Final")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gastos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idviaje");

                    b.ToTable("Viajes");
                });
#pragma warning restore 612, 618
        }
    }
}
